[font]
size = 11.5
normal = { family = "JetBrainsMonoNerdFontMono", style = "Regular" }

[general]
import = [ "~/.config/alacritty/themes/snazzy.toml"]
# [window]
# dimensions = { columns = 120, lines = 40 }
# startup_mode = "Maximized"
