import = [ "~/.config/alacritty/themes/snazzy.toml"]
[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
[window]
dimensions = { columns = 120, lines = 40 }
startup_mode = "Maximized"
